### ISSUE TITLE
Spaces not properly marked as separators

### ISSUE THREAD

**Issue by asgerb** [tomasc/semantic_date_time_tags#2]
When using a format where date, month and year are separated by spaces, the spaces are not marked as separators.

They should be marked the same as other separators (`.`, `–`, `/` etc.):
```html
<span class="separator"> </span>
```

**Comment by tomasc** [comment]
if you add failing test i can try to fix it

**Comment by asgerb** [comment]
pushed failing tests to master

**Comment by tomasc** [comment]
fixed by 42f02be77102a2fa77f06f4983d4759fceffed80
